2018-04-29 14:02:43,032 [Thread-7:7416] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/login HTTP/1.1" 405 11703
2018-04-29 14:02:43,465 [Thread-6:19912] [django.request:93] [base:get_response] [WARNING]- Not Found: /favicon.ico
2018-04-29 14:02:43,467 [Thread-6:19912] [django.server:124] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 2079
2018-04-29 14:03:00,248 [Thread-8:8216] [django:166] [views:post] [INFO]- try to login
2018-04-29 14:03:00,342 [Thread-8:8216] [django:175] [views:post] [INFO]- login successfully
2018-04-29 14:03:00,374 [Thread-8:8216] [django.server:124] [basehttp:log_message] [INFO]- "POST /api/login HTTP/1.1" 200 11759
2018-04-29 14:04:59,216 [Thread-9:18580] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/register_student HTTP/1.1" 405 14001
2018-04-29 14:09:22,362 [Thread-15:1320] [django:27] [views:post] [INFO]- try to register student account
2018-04-29 14:09:22,368 [Thread-15:1320] [django:28] [serializers:create] [INFO]- create account
2018-04-29 14:09:22,456 [Thread-15:1320] [django:31] [views:post] [INFO]- account register successfully, username:3150103107
2018-04-29 14:09:22,493 [Thread-15:1320] [django.server:124] [basehttp:log_message] [INFO]- "POST /api/register_student HTTP/1.1" 201 14001
2018-04-29 14:11:27,082 [Thread-16:12552] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/register_faculty HTTP/1.1" 405 13515
2018-04-29 14:11:49,302 [Thread-22:5504] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/register_student HTTP/1.1" 405 14001
2018-04-29 14:11:53,815 [Thread-23:14420] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/register_faculty HTTP/1.1" 405 13515
2018-04-29 14:13:14,371 [Thread-29:11064] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/register_student HTTP/1.1" 405 14001
2018-04-29 14:13:15,754 [Thread-30:15604] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/student/ HTTP/1.1" 200 15826
2018-04-29 14:13:52,113 [Thread-37:19572] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/student/ HTTP/1.1" 200 15826
2018-04-29 14:14:02,212 [Thread-43:14576] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/student/ HTTP/1.1" 200 15826
2018-04-29 14:15:31,737 [Thread-49:12724] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/register_student HTTP/1.1" 405 14001
2018-04-29 14:16:00,533 [Thread-55:16552] [django:27] [views:post] [INFO]- try to register student account
2018-04-29 14:16:00,535 [Thread-55:16552] [django:28] [serializers:create] [INFO]- create account
2018-04-29 14:16:00,621 [Thread-55:16552] [django:31] [views:post] [INFO]- account register successfully, username:stu1
2018-04-29 14:16:00,675 [Thread-55:16552] [django.server:124] [basehttp:log_message] [INFO]- "POST /api/register_student HTTP/1.1" 201 14001
2018-04-29 14:16:26,827 [Thread-56:17708] [django:27] [views:post] [INFO]- try to register student account
2018-04-29 14:16:26,830 [Thread-56:17708] [django:28] [serializers:create] [INFO]- create account
2018-04-29 14:16:26,919 [Thread-56:17708] [django:31] [views:post] [INFO]- account register successfully, username:stu2
2018-04-29 14:16:26,955 [Thread-56:17708] [django.server:124] [basehttp:log_message] [INFO]- "POST /api/register_student HTTP/1.1" 201 14001
2018-04-29 14:16:33,018 [Thread-57:16156] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/register_faculty HTTP/1.1" 405 13515
2018-04-29 14:17:11,435 [Thread-63:18428] [django:44] [views:post] [INFO]- try to register faculty account
2018-04-29 14:17:11,437 [Thread-63:18428] [django:28] [serializers:create] [INFO]- create account
2018-04-29 14:17:11,520 [Thread-63:18428] [django:48] [views:post] [INFO]- account register successfully, username:fac1
2018-04-29 14:17:11,557 [Thread-63:18428] [django.server:124] [basehttp:log_message] [INFO]- "POST /api/register_faculty HTTP/1.1" 201 13515
2018-04-29 14:17:31,572 [Thread-64:17832] [django:44] [views:post] [INFO]- try to register faculty account
2018-04-29 14:17:31,575 [Thread-64:17832] [django:28] [serializers:create] [INFO]- create account
2018-04-29 14:17:31,658 [Thread-64:17832] [django:48] [views:post] [INFO]- account register successfully, username:fac2
2018-04-29 14:17:31,693 [Thread-64:17832] [django.server:124] [basehttp:log_message] [INFO]- "POST /api/register_faculty HTTP/1.1" 201 13515
2018-04-29 14:17:36,779 [Thread-65:7580] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/register_staff HTTP/1.1" 405 13256
2018-04-29 14:18:00,902 [Thread-71:11796] [django:61] [views:post] [INFO]- try to register staff account
2018-04-29 14:18:00,904 [Thread-71:11796] [django:28] [serializers:create] [INFO]- create account
2018-04-29 14:18:01,024 [Thread-71:11796] [django:65] [views:post] [INFO]- account register successfully, username:staff1
2018-04-29 14:18:01,065 [Thread-71:11796] [django.server:124] [basehttp:log_message] [INFO]- "POST /api/register_staff HTTP/1.1" 201 13256
2018-04-29 14:18:18,849 [Thread-72:18664] [django:61] [views:post] [INFO]- try to register staff account
2018-04-29 14:18:18,851 [Thread-72:18664] [django:28] [serializers:create] [INFO]- create account
2018-04-29 14:18:18,999 [Thread-72:18664] [django:65] [views:post] [INFO]- account register successfully, username:staff2
2018-04-29 14:18:19,043 [Thread-72:18664] [django.server:124] [basehttp:log_message] [INFO]- "POST /api/register_staff HTTP/1.1" 201 13256
2018-04-29 14:18:37,174 [Thread-73:13296] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/register_admin HTTP/1.1" 405 12796
2018-04-29 14:19:09,602 [Thread-80:808] [django:78] [views:post] [INFO]- try to register admin account
2018-04-29 14:19:09,620 [Thread-80:808] [django:82] [views:post] [INFO]- account register successfully, username:admin1
2018-04-29 14:19:09,650 [Thread-80:808] [django.server:124] [basehttp:log_message] [INFO]- "POST /api/register_admin HTTP/1.1" 201 12796
2018-04-29 14:19:43,413 [Thread-81:8904] [django:78] [views:post] [INFO]- try to register admin account
2018-04-29 14:19:43,431 [Thread-81:8904] [django:82] [views:post] [INFO]- account register successfully, username:admin2
2018-04-29 14:19:43,462 [Thread-81:8904] [django.server:124] [basehttp:log_message] [INFO]- "POST /api/register_admin HTTP/1.1" 201 12796
2018-04-29 14:20:08,268 [Thread-82:5200] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/login HTTP/1.1" 405 11736
2018-04-29 14:20:31,131 [Thread-89:15356] [django:166] [views:post] [INFO]- try to login
2018-04-29 14:20:31,275 [Thread-89:15356] [django:175] [views:post] [INFO]- login successfully
2018-04-29 14:20:31,326 [Thread-89:15356] [django.server:124] [basehttp:log_message] [INFO]- "POST /api/login HTTP/1.1" 200 11777
2018-04-29 14:21:50,501 [Thread-90:12572] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/student/ HTTP/1.1" 403 9415
2018-04-29 14:21:54,722 [Thread-91:15556] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/student/stu2 HTTP/1.1" 301 0
2018-04-29 14:21:54,764 [Thread-92:5832] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/student/stu2/ HTTP/1.1" 403 10902
2018-04-29 14:22:05,132 [Thread-97:2080] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/student/stu3 HTTP/1.1" 301 0
2018-04-29 14:22:05,178 [Thread-98:9112] [django.request:93] [base:get_response] [WARNING]- Not Found: /api/student/stu3/
2018-04-29 14:22:05,179 [Thread-98:9112] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/student/stu3/ HTTP/1.1" 404 16698
2018-04-29 14:22:07,491 [Thread-99:708] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/student/stu1 HTTP/1.1" 301 0
2018-04-29 14:22:07,541 [Thread-100:8684] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/student/stu1/ HTTP/1.1" 200 17286
2018-04-29 14:24:05,161 [Thread-105:1052] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/login HTTP/1.1" 405 11736
2018-04-29 14:24:16,712 [Thread-112:18256] [django:166] [views:post] [INFO]- try to login
2018-04-29 14:24:16,715 [Thread-112:18256] [django:188] [views:post] [INFO]- login failed
2018-04-29 14:24:16,737 [Thread-112:18256] [django.server:124] [basehttp:log_message] [WARNING]- "POST /api/login HTTP/1.1" 401 11772
2018-04-29 14:24:34,480 [Thread-113:10476] [django:166] [views:post] [INFO]- try to login
2018-04-29 14:24:34,486 [Thread-113:10476] [django:188] [views:post] [INFO]- login failed
2018-04-29 14:24:34,524 [Thread-113:10476] [django.server:124] [basehttp:log_message] [WARNING]- "POST /api/login HTTP/1.1" 401 11772
2018-04-29 14:24:42,993 [Thread-114:16492] [django:166] [views:post] [INFO]- try to login
2018-04-29 14:24:42,996 [Thread-114:16492] [django:188] [views:post] [INFO]- login failed
2018-04-29 14:24:43,021 [Thread-114:16492] [django.server:124] [basehttp:log_message] [WARNING]- "POST /api/login HTTP/1.1" 401 11772
2018-04-29 14:24:52,948 [Thread-115:17904] [django:166] [views:post] [INFO]- try to login
2018-04-29 14:24:52,951 [Thread-115:17904] [django:188] [views:post] [INFO]- login failed
2018-04-29 14:24:52,973 [Thread-115:17904] [django.server:124] [basehttp:log_message] [WARNING]- "POST /api/login HTTP/1.1" 401 11772
2018-04-29 14:25:24,217 [Thread-116:16328] [django:166] [views:post] [INFO]- try to login
2018-04-29 14:25:24,219 [Thread-116:16328] [django:194] [views:post] [INFO]- login failed
2018-04-29 14:25:24,243 [Thread-116:16328] [django.server:124] [basehttp:log_message] [WARNING]- "POST /api/login HTTP/1.1" 400 11738
2018-04-29 14:28:40,119 [Thread-1:16396] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/login HTTP/1.1" 405 11736
2018-04-29 14:28:45,179 [Thread-3:14244] [django:166] [views:post] [INFO]- try to login
2018-04-29 14:28:45,278 [Thread-3:14244] [django:175] [views:post] [INFO]- login successfully
2018-04-29 14:28:45,314 [Thread-3:14244] [django.server:124] [basehttp:log_message] [INFO]- "POST /api/login HTTP/1.1" 200 11759
2018-04-29 14:28:50,118 [Thread-8:14332] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/register_student HTTP/1.1" 405 14001
2018-04-29 14:28:51,649 [Thread-9:14696] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/register_admin HTTP/1.1" 405 12796
2018-04-29 14:29:08,256 [Thread-15:2696] [django:78] [views:post] [INFO]- try to register admin account
2018-04-29 14:29:08,349 [Thread-15:2696] [django:82] [views:post] [INFO]- account register successfully, username:admin1
2018-04-29 14:29:08,382 [Thread-15:2696] [django.server:124] [basehttp:log_message] [INFO]- "POST /api/register_admin HTTP/1.1" 201 12796
2018-04-29 14:29:22,556 [Thread-16:1744] [django:78] [views:post] [INFO]- try to register admin account
2018-04-29 14:29:22,637 [Thread-16:1744] [django:82] [views:post] [INFO]- account register successfully, username:admin2
2018-04-29 14:29:22,664 [Thread-16:1744] [django.server:124] [basehttp:log_message] [INFO]- "POST /api/register_admin HTTP/1.1" 201 12796
2018-04-29 14:29:25,673 [Thread-17:20376] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/login HTTP/1.1" 405 11736
2018-04-29 14:29:32,546 [Thread-18:5232] [django:166] [views:post] [INFO]- try to login
2018-04-29 14:29:32,640 [Thread-18:5232] [django:175] [views:post] [INFO]- login successfully
2018-04-29 14:29:32,673 [Thread-18:5232] [django.server:124] [basehttp:log_message] [INFO]- "POST /api/login HTTP/1.1" 200 11779
2018-04-29 14:29:36,791 [Thread-24:6064] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/student/ HTTP/1.1" 200 16355
2018-04-29 14:30:30,210 [Thread-31:16192] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/faculty HTTP/1.1" 301 0
2018-04-29 14:30:30,263 [Thread-32:14472] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/faculty/ HTTP/1.1" 200 15628
2018-04-29 14:31:13,127 [Thread-37:10400] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/student/ HTTP/1.1" 200 16355
2018-04-29 14:31:24,695 [Thread-43:16268] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/student/stu1/ HTTP/1.1" 200 17288
2018-04-29 14:33:05,112 [Thread-49:19184] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/student/faculty HTTP/1.1" 301 0
2018-04-29 14:33:05,165 [Thread-50:17440] [django.request:93] [base:get_response] [WARNING]- Not Found: /api/student/faculty/
2018-04-29 14:33:05,165 [Thread-50:17440] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/student/faculty/ HTTP/1.1" 404 16727
2018-04-29 14:33:08,428 [Thread-55:9596] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/faculty/ HTTP/1.1" 200 15628
2018-04-29 14:33:52,809 [Thread-61:16148] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/faculty/fac1 HTTP/1.1" 301 0
2018-04-29 14:33:52,868 [Thread-62:17476] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/faculty/fac1/ HTTP/1.1" 200 16638
2018-04-29 14:34:17,633 [Thread-67:8204] [django.request:93] [base:get_response] [WARNING]- Not Found: /api/staff1
2018-04-29 14:34:17,633 [Thread-67:8204] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/staff1 HTTP/1.1" 404 9218
2018-04-29 14:34:20,442 [Thread-68:18384] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/staff HTTP/1.1" 301 0
2018-04-29 14:34:20,486 [Thread-69:17956] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/staff/ HTTP/1.1" 200 15228
2018-04-29 14:39:45,661 [Thread-73:9080] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/staff/staff1 HTTP/1.1" 301 0
2018-04-29 14:39:45,709 [Thread-74:19460] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/staff/staff1/ HTTP/1.1" 200 16284
2018-04-29 14:40:01,642 [Thread-78:17740] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/admin HTTP/1.1" 301 0
2018-04-29 14:40:01,701 [Thread-79:10740] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/admin/ HTTP/1.1" 200 15152
2018-04-29 14:40:29,049 [Thread-83:11340] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/admin/xixi HTTP/1.1" 301 0
2018-04-29 14:40:29,126 [Thread-84:2820] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/admin/xixi/ HTTP/1.1" 200 15850
2018-04-29 14:42:31,064 [Thread-88:15400] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/login HTTP/1.1" 405 11738
2018-04-29 14:42:40,244 [Thread-95:13896] [django:166] [views:post] [INFO]- try to login
2018-04-29 14:42:40,336 [Thread-95:13896] [django:175] [views:post] [INFO]- login successfully
2018-04-29 14:42:40,369 [Thread-95:13896] [django.server:124] [basehttp:log_message] [INFO]- "POST /api/login HTTP/1.1" 200 11777
2018-04-29 14:42:43,760 [Thread-96:14588] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/student/ HTTP/1.1" 403 9415
2018-04-29 14:43:27,722 [Thread-102:5956] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/student/stu2/ HTTP/1.1" 403 10902
2018-04-29 14:43:30,197 [Thread-103:14124] [django.request:93] [base:get_response] [WARNING]- Not Found: /api/student/stu3/
2018-04-29 14:43:30,198 [Thread-103:14124] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/student/stu3/ HTTP/1.1" 404 16698
2018-04-29 14:43:39,289 [Thread-109:9072] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/student/stu1/ HTTP/1.1" 200 17286
2018-04-29 14:43:44,566 [Thread-110:16000] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/student/stu2/ HTTP/1.1" 403 10902
2018-04-29 14:44:04,679 [Thread-115:9392] [django.request:93] [base:get_response] [WARNING]- Not Found: /api/student/stu3/
2018-04-29 14:44:04,680 [Thread-115:9392] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/student/stu3/ HTTP/1.1" 404 16698
2018-04-29 14:44:34,774 [Thread-120:10708] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/login HTTP/1.1" 405 11736
2018-04-29 14:44:42,916 [Thread-127:13248] [django:166] [views:post] [INFO]- try to login
2018-04-29 14:44:42,987 [Thread-127:13248] [django:188] [views:post] [INFO]- login failed
2018-04-29 14:44:43,012 [Thread-127:13248] [django.server:124] [basehttp:log_message] [WARNING]- "POST /api/login HTTP/1.1" 401 11772
2018-04-29 14:44:54,733 [Thread-128:15900] [django:166] [views:post] [INFO]- try to login
2018-04-29 14:44:54,824 [Thread-128:15900] [django:175] [views:post] [INFO]- login successfully
2018-04-29 14:44:54,857 [Thread-128:15900] [django.server:124] [basehttp:log_message] [INFO]- "POST /api/login HTTP/1.1" 200 11779
2018-04-29 14:44:58,538 [Thread-129:14252] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/staff/ HTTP/1.1" 403 9395
2018-04-29 14:45:02,342 [Thread-130:6852] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/staff/staff1/ HTTP/1.1" 200 16284
2018-04-29 14:45:04,156 [Thread-131:11636] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/staff/staff2 HTTP/1.1" 301 0
2018-04-29 14:45:04,193 [Thread-132:16372] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/staff/staff2/ HTTP/1.1" 403 10882
2018-04-29 14:46:40,820 [Thread-137:3364] [django.request:93] [base:get_response] [WARNING]- Not Found: /api/update_password
2018-04-29 14:46:40,821 [Thread-137:3364] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/update_password HTTP/1.1" 404 9245
2018-04-29 14:46:49,916 [Thread-138:16928] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/password_update HTTP/1.1" 405 11761
2018-04-29 14:47:59,336 [Thread-1:15556] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/register_student HTTP/1.1" 403 8128
2018-04-29 14:48:01,202 [Thread-3:11316] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/register_course HTTP/1.1" 405 12820
2018-04-29 14:48:14,741 [Thread-9:18904] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/login HTTP/1.1" 405 11738
2018-04-29 14:48:21,002 [Thread-10:16088] [django:166] [views:post] [INFO]- try to login
2018-04-29 14:48:21,093 [Thread-10:16088] [django:175] [views:post] [INFO]- login successfully
2018-04-29 14:48:21,163 [Thread-10:16088] [django.server:124] [basehttp:log_message] [INFO]- "POST /api/login HTTP/1.1" 200 11777
2018-04-29 14:48:26,483 [Thread-16:6544] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/register_course HTTP/1.1" 405 8421
2018-04-29 14:49:22,109 [Thread-22:8064] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/course/ HTTP/1.1" 200 9601
2018-04-29 14:49:36,905 [Thread-28:19556] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/update_password HTTP/1.1" 405 11759
2018-04-29 14:49:43,758 [Thread-29:13936] [django:145] [views:put] [INFO]- try to update password
2018-04-29 14:49:43,760 [Thread-29:13936] [django:140] [serializers:validate_new_password] [INFO]- update account password
2018-04-29 14:49:43,764 [Thread-29:13936] [django:159] [views:put] [INFO]- password update failed
2018-04-29 14:49:43,785 [Thread-29:13936] [django.server:124] [basehttp:log_message] [WARNING]- "PUT /api/update_password HTTP/1.1" 400 11890
2018-04-29 14:49:52,640 [Thread-34:7460] [django:145] [views:put] [INFO]- try to update password
2018-04-29 14:49:52,641 [Thread-34:7460] [django:140] [serializers:validate_new_password] [INFO]- update account password
2018-04-29 14:49:52,729 [Thread-34:7460] [django.server:124] [basehttp:log_message] [WARNING]- "PUT /api/update_password HTTP/1.1" 400 11742
2018-04-29 14:50:59,284 [Thread-35:10468] [django:145] [views:put] [INFO]- try to update password
2018-04-29 14:50:59,286 [Thread-35:10468] [django:140] [serializers:validate_new_password] [INFO]- update account password
2018-04-29 14:50:59,286 [Thread-35:10468] [django:159] [views:put] [INFO]- password update failed
2018-04-29 14:50:59,307 [Thread-35:10468] [django.server:124] [basehttp:log_message] [WARNING]- "PUT /api/update_password HTTP/1.1" 400 11888
2018-04-29 14:51:35,181 [Thread-36:13200] [django:145] [views:put] [INFO]- try to update password
2018-04-29 14:51:35,182 [Thread-36:13200] [django:140] [serializers:validate_new_password] [INFO]- update account password
2018-04-29 14:51:35,390 [Thread-36:13200] [django:156] [views:put] [INFO]- password update successfully
2018-04-29 14:51:35,411 [Thread-36:13200] [django.server:124] [basehttp:log_message] [INFO]- "PUT /api/update_password HTTP/1.1" 200 11738
2018-04-29 14:52:21,624 [Thread-37:8440] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/student/stu1/ HTTP/1.1" 403 9549
2018-04-29 14:52:29,579 [Thread-44:19336] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/login HTTP/1.1" 405 11703
2018-04-29 14:52:39,362 [Thread-50:15500] [django:166] [views:post] [INFO]- try to login
2018-04-29 14:52:39,481 [Thread-50:15500] [django:175] [views:post] [INFO]- login successfully
2018-04-29 14:52:39,515 [Thread-50:15500] [django.server:124] [basehttp:log_message] [INFO]- "POST /api/login HTTP/1.1" 200 11759
2018-04-29 14:52:43,520 [Thread-51:7248] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/student/stu1/ HTTP/1.1" 200 17286
2018-04-29 14:53:04,905 [Thread-57:17512] [django:159] [serializers:update] [INFO]- update student info
2018-04-29 14:53:04,952 [Thread-57:17512] [django.server:124] [basehttp:log_message] [INFO]- "PUT /api/student/stu1/ HTTP/1.1" 200 17290
2018-04-29 14:53:31,722 [Thread-58:16032] [django:159] [serializers:update] [INFO]- update student info
2018-04-29 14:53:31,758 [Thread-58:16032] [django.server:124] [basehttp:log_message] [WARNING]- "PUT /api/student/stu1/ HTTP/1.1" 400 16717
2018-04-29 15:01:44,851 [Thread-1:14484] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/login HTTP/1.1" 405 11736
2018-04-29 15:01:55,200 [Thread-9:14568] [django:166] [views:post] [INFO]- try to login
2018-04-29 15:01:55,294 [Thread-9:14568] [django:175] [views:post] [INFO]- login successfully
2018-04-29 15:01:55,332 [Thread-9:14568] [django.server:124] [basehttp:log_message] [INFO]- "POST /api/login HTTP/1.1" 200 11777
2018-04-29 15:01:59,555 [Thread-10:8556] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/register_student HTTP/1.1" 403 8126
2018-04-29 15:02:01,557 [Thread-11:11684] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/register_course HTTP/1.1" 405 12818
2018-04-29 15:03:23,662 [Thread-18:19148] [django:95] [views:post] [INFO]- try to register course
2018-04-29 15:03:23,665 [Thread-18:19148] [django:96] [serializers:create] [INFO]- create course
2018-04-29 15:03:23,677 [Thread-18:19148] [django:99] [views:post] [INFO]- course register successfully, name:cs211n
2018-04-29 15:03:23,705 [Thread-18:19148] [django.server:124] [basehttp:log_message] [INFO]- "POST /api/register_course HTTP/1.1" 201 12816
2018-04-29 15:03:27,894 [Thread-19:12516] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/course/ HTTP/1.1" 200 14766
2018-04-29 15:05:11,631 [Thread-26:9076] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/register_course HTTP/1.1" 405 12818
2018-04-29 15:05:27,907 [Thread-32:10412] [django:95] [views:post] [INFO]- try to register course
2018-04-29 15:05:27,908 [Thread-32:10412] [django:96] [serializers:create] [INFO]- create course
2018-04-29 15:05:27,917 [Thread-32:10412] [django:99] [views:post] [INFO]- course register successfully, name:cs231
2018-04-29 15:05:27,952 [Thread-32:10412] [django.server:124] [basehttp:log_message] [INFO]- "POST /api/register_course HTTP/1.1" 201 12816
2018-04-29 15:05:31,134 [Thread-33:19460] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/course/ HTTP/1.1" 200 15068
2018-04-29 15:06:01,177 [Thread-40:19168] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/course/course1 HTTP/1.1" 301 0
2018-04-29 15:06:01,223 [Thread-41:5276] [django.request:93] [base:get_response] [WARNING]- Not Found: /api/course/course1/
2018-04-29 15:06:01,224 [Thread-41:5276] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/course/course1/ HTTP/1.1" 404 15898
2018-04-29 15:06:04,538 [Thread-42:13752] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/course/1 HTTP/1.1" 301 0
2018-04-29 15:06:04,591 [Thread-43:5436] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/course/1/ HTTP/1.1" 200 16079
2018-04-29 15:06:49,428 [Thread-50:8216] [django:324] [serializers:update] [INFO]- update course info
2018-04-29 15:06:49,428 [Thread-50:8216] [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/course/1/
Traceback (most recent call last):
  File "D:\tools\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\tools\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\tools\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\tools\Anaconda3\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\tools\Anaconda3\lib\site-packages\rest_framework\viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\tools\Anaconda3\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "D:\tools\Anaconda3\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\tools\Anaconda3\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tools\Anaconda3\lib\site-packages\rest_framework\mixins.py", line 70, in update
    self.perform_update(serializer)
  File "D:\tools\Anaconda3\lib\site-packages\rest_framework\mixins.py", line 80, in perform_update
    serializer.save()
  File "D:\tools\Anaconda3\lib\site-packages\rest_framework\serializers.py", line 209, in save
    self.instance = self.update(self.instance, validated_data)
  File "D:\tools\Anaconda3\lib\contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "C:\Users\c\Desktop\InfoSys\InfoSys-back\authentication\serializers.py", line 325, in update
    Course.objects.filter(course_id=instance.id).delete()
AttributeError: 'Course' object has no attribute 'id'
2018-04-29 15:06:51,276 [Thread-50:8216] [django.server:124] [basehttp:log_message] [ERROR]- "PUT /api/course/1/ HTTP/1.1" 500 115862
2018-04-29 15:07:35,684 [Thread-1:2824] [django.request:93] [base:get_response] [WARNING]- Not Found: /api/course/course1/
2018-04-29 15:07:35,685 [Thread-1:2824] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/course/course1/ HTTP/1.1" 404 15898
2018-04-29 15:07:40,157 [Thread-3:20320] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/course/1/ HTTP/1.1" 200 16079
2018-04-29 15:07:43,086 [Thread-10:8220] [django:324] [serializers:update] [INFO]- update course info
2018-04-29 15:07:43,137 [Thread-10:8220] [django.server:124] [basehttp:log_message] [WARNING]- "PUT /api/course/1/ HTTP/1.1" 400 15853
2018-04-29 15:07:52,596 [Thread-11:2764] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/login HTTP/1.1" 405 11736
2018-04-29 15:08:00,792 [Thread-12:9088] [django:166] [views:post] [INFO]- try to login
2018-04-29 15:08:00,862 [Thread-12:9088] [django:188] [views:post] [INFO]- login failed
2018-04-29 15:08:00,885 [Thread-12:9088] [django.server:124] [basehttp:log_message] [WARNING]- "POST /api/login HTTP/1.1" 401 11772
2018-04-29 15:08:12,477 [Thread-18:10404] [django:166] [views:post] [INFO]- try to login
2018-04-29 15:08:12,594 [Thread-18:10404] [django:175] [views:post] [INFO]- login successfully
2018-04-29 15:08:12,634 [Thread-18:10404] [django.server:124] [basehttp:log_message] [INFO]- "POST /api/login HTTP/1.1" 200 11779
2018-04-29 15:08:18,073 [Thread-19:11416] [django.request:93] [base:get_response] [WARNING]- Not Found: /api/login/course
2018-04-29 15:08:18,074 [Thread-19:11416] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/login/course HTTP/1.1" 404 9236
2018-04-29 15:08:21,611 [Thread-25:17708] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/course/ HTTP/1.1" 200 15070
2018-04-29 15:08:26,557 [Thread-26:10072] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/course/1/ HTTP/1.1" 200 16081
2018-04-29 15:08:39,420 [Thread-33:19220] [django:324] [serializers:update] [INFO]- update course info
2018-04-29 15:08:39,461 [Thread-33:19220] [django.server:124] [basehttp:log_message] [INFO]- "PUT /api/course/1/ HTTP/1.1" 200 16081
2018-05-02 03:16:23,191 [Thread-1:123145312813056] [django.request:93] [base:get_response] [WARNING]- Not Found: /
2018-05-02 03:16:23,192 [Thread-1:123145312813056] [django.server:124] [basehttp:log_message] [WARNING]- "GET / HTTP/1.1" 404 2024
2018-05-02 03:16:28,089 [Thread-3:123145312813056] [django.request:93] [base:get_response] [WARNING]- Not Found: /
2018-05-02 03:16:28,089 [Thread-3:123145312813056] [django.server:124] [basehttp:log_message] [WARNING]- "GET / HTTP/1.1" 404 2024
2018-05-02 03:16:28,747 [Thread-4:123145312813056] [django.request:93] [base:get_response] [WARNING]- Not Found: /account/logout/
2018-05-02 03:16:28,747 [Thread-4:123145312813056] [django.server:124] [basehttp:log_message] [WARNING]- "GET /account/logout/ HTTP/1.1" 404 2087
2018-05-02 03:16:28,943 [Thread-5:123145312813056] [django.request:93] [base:get_response] [WARNING]- Not Found: /api/create_user
2018-05-02 03:16:28,944 [Thread-5:123145312813056] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/create_user HTTP/1.1" 404 9229
2018-05-02 03:16:29,145 [Thread-6:123145312813056] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/ HTTP/1.1" 200 10124
2018-05-02 03:16:29,172 [Thread-8:123145318068224] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
2018-05-02 03:16:29,175 [Thread-7:123145312813056] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121200
2018-05-02 03:16:29,180 [Thread-9:123145323323392] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
2018-05-02 03:16:29,185 [Thread-10:123145328578560] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
2018-05-02 03:16:29,193 [Thread-12:123145312813056] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
2018-05-02 03:16:29,205 [Thread-13:123145318068224] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1735
2018-05-02 03:16:29,209 [Thread-14:123145323323392] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1262
2018-05-02 03:16:29,211 [Thread-11:123145333833728] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 200 86927
2018-05-02 03:16:29,219 [Thread-15:123145312813056] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 37045
2018-05-02 03:16:29,225 [Thread-16:123145318068224] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
2018-05-02 03:16:29,227 [Thread-17:123145312813056] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
2018-05-02 03:16:29,459 [Thread-18:123145312813056] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/ HTTP/1.1" 200 10124
2018-05-02 03:16:38,727 [Thread-19:123145312813056] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/course/ HTTP/1.1" 403 9366
2018-05-02 03:16:46,313 [Thread-20:123145312813056] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/login HTTP/1.1" 405 11703
2018-05-02 03:16:47,438 [Thread-21:123145312813056] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/login HTTP/1.1" 405 11703
2018-05-02 03:16:55,133 [Thread-22:123145312813056] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/ HTTP/1.1" 200 10124
2018-05-02 03:16:56,484 [Thread-23:123145312813056] [django.request:93] [base:get_response] [WARNING]- Not Found: /api/create_user
2018-05-02 03:16:56,485 [Thread-23:123145312813056] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/create_user HTTP/1.1" 404 9229
2018-05-02 03:16:57,205 [Thread-24:123145312813056] [django.request:93] [base:get_response] [WARNING]- Not Found: /api/create_user
2018-05-02 03:16:57,205 [Thread-24:123145312813056] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/create_user HTTP/1.1" 404 9229
2018-05-02 03:17:00,626 [Thread-25:123145312813056] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/ HTTP/1.1" 200 10124
2018-05-02 03:17:00,766 [Thread-26:123145312813056] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/student/315010/ HTTP/1.1" 403 9559
2018-05-02 03:17:02,342 [Thread-27:123145312813056] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/ HTTP/1.1" 200 10124
2018-05-02 03:17:03,433 [Thread-28:123145312813056] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/student/315010/ HTTP/1.1" 403 9559
2018-05-02 03:17:05,991 [Thread-29:123145312813056] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/student/ HTTP/1.1" 403 9377
2018-05-02 03:17:08,780 [Thread-30:123145312813056] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/student/register HTTP/1.1" 301 0
2018-05-02 03:17:08,841 [Thread-31:123145312813056] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/student/register/ HTTP/1.1" 403 9569
2018-05-02 04:39:08,985 [Thread-1:123145312813056] [django.request:93] [base:get_response] [WARNING]- Not Found: /
2018-05-02 04:39:08,987 [Thread-1:123145312813056] [django.server:124] [basehttp:log_message] [WARNING]- "GET / HTTP/1.1" 404 2028
2018-05-02 04:39:11,568 [Thread-3:123145312813056] [django.request:93] [base:get_response] [WARNING]- Not Found: /
2018-05-02 04:39:11,569 [Thread-3:123145312813056] [django.server:124] [basehttp:log_message] [WARNING]- "GET / HTTP/1.1" 404 2028
2018-05-02 04:39:12,398 [Thread-4:123145312813056] [django.request:93] [base:get_response] [WARNING]- Not Found: /account/logout/
2018-05-02 04:39:12,398 [Thread-4:123145312813056] [django.server:124] [basehttp:log_message] [WARNING]- "GET /account/logout/ HTTP/1.1" 404 2091
2018-05-02 04:39:14,052 [Thread-5:123145312813056] [django.request:93] [base:get_response] [WARNING]- Not Found: /account/logout/
2018-05-02 04:39:14,052 [Thread-5:123145312813056] [django.server:124] [basehttp:log_message] [WARNING]- "GET /account/logout/ HTTP/1.1" 404 2091
2018-05-02 04:39:14,142 [Thread-6:123145312813056] [django.request:93] [base:get_response] [WARNING]- Not Found: /api/create_user
2018-05-02 04:39:14,143 [Thread-6:123145312813056] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/create_user HTTP/1.1" 404 2091
2018-05-02 04:39:14,389 [Thread-7:123145312813056] [django.request:93] [base:get_response] [WARNING]- Not Found: /api/
2018-05-02 04:39:14,389 [Thread-7:123145312813056] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/ HTTP/1.1" 404 2058
2018-05-02 04:39:38,346 [Thread-8:123145312813056] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/info/register_student HTTP/1.1" 403 8103
2018-05-02 04:39:48,342 [Thread-9:123145312813056] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/info/register_student HTTP/1.1" 403 8103
2018-05-02 04:39:51,242 [Thread-10:123145312813056] [django.request:93] [base:get_response] [WARNING]- Not Found: /api/info/log_in
2018-05-02 04:39:51,242 [Thread-10:123145312813056] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/info/log_in HTTP/1.1" 404 9388
2018-05-02 04:40:00,117 [Thread-11:123145312813056] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/info/login HTTP/1.1" 405 11733
2018-05-02 04:40:04,563 [Thread-12:123145312813056] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/info/login HTTP/1.1" 405 11733
2018-05-02 04:40:11,913 [Thread-13:123145312813056] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/info/is_token_valid HTTP/1.1" 405 11752
2018-05-02 14:03:10,453 [Thread-1:8732] [django.request:93] [base:get_response] [WARNING]- Not Found: /
2018-05-02 14:03:10,455 [Thread-1:8732] [django.server:124] [basehttp:log_message] [WARNING]- "GET / HTTP/1.1" 404 2023
2018-05-02 14:03:10,936 [Thread-3:9092] [django.request:93] [base:get_response] [WARNING]- Not Found: /favicon.ico
2018-05-02 14:03:10,937 [Thread-3:9092] [django.server:124] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 2074
2018-05-02 14:03:14,940 [Thread-4:7736] [django.request:93] [base:get_response] [WARNING]- Not Found: /api/online_testing/question/
2018-05-02 14:03:14,941 [Thread-4:7736] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/online_testing/question/ HTTP/1.1" 404 9267
2018-05-02 14:03:24,655 [Thread-5:1684] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/login HTTP/1.1" 405 11703
2018-05-02 14:03:36,106 [Thread-7:11192] [django:166] [views:post] [INFO]- try to login
2018-05-02 14:03:36,214 [Thread-7:11192] [django:188] [views:post] [INFO]- login failed
2018-05-02 14:03:36,245 [Thread-7:11192] [django.server:124] [basehttp:log_message] [WARNING]- "POST /api/login HTTP/1.1" 401 11739
2018-05-02 14:03:59,282 [Thread-8:6792] [django.request:93] [base:get_response] [WARNING]- Not Found: /api/register
2018-05-02 14:03:59,286 [Thread-8:6792] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/register HTTP/1.1" 404 9219
2018-05-02 14:04:07,960 [Thread-9:7980] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/register_admin HTTP/1.1" 403 8078
2018-05-02 14:04:19,571 [Thread-14:5892] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/register_student HTTP/1.1" 403 8088
2018-05-02 14:04:26,383 [Thread-19:1888] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/login HTTP/1.1" 405 11703
2018-05-02 14:04:39,245 [Thread-23:9392] [django:166] [views:post] [INFO]- try to login
2018-05-02 14:04:39,374 [Thread-23:9392] [django:188] [views:post] [INFO]- login failed
2018-05-02 14:04:39,413 [Thread-23:9392] [django.server:124] [basehttp:log_message] [WARNING]- "POST /api/login HTTP/1.1" 401 11739
2018-05-02 14:15:29,955 [Thread-1:3268] [django:166] [views:post] [INFO]- try to login
2018-05-02 14:15:30,061 [Thread-1:3268] [django:188] [views:post] [INFO]- login failed
2018-05-02 14:15:30,124 [Thread-1:3268] [django.server:124] [basehttp:log_message] [WARNING]- "POST /api/login HTTP/1.1" 401 11739
2018-05-02 14:15:34,360 [Thread-3:8408] [django:166] [views:post] [INFO]- try to login
2018-05-02 14:15:34,485 [Thread-3:8408] [django:188] [views:post] [INFO]- login failed
2018-05-02 14:15:34,520 [Thread-3:8408] [django.server:124] [basehttp:log_message] [WARNING]- "POST /api/login HTTP/1.1" 401 11739
2018-05-02 14:16:46,651 [Thread-4:10532] [django:166] [views:post] [INFO]- try to login
2018-05-02 14:16:46,755 [Thread-4:10532] [django:188] [views:post] [INFO]- login failed
2018-05-02 14:16:46,784 [Thread-4:10532] [django.server:124] [basehttp:log_message] [WARNING]- "POST /api/login HTTP/1.1" 401 11739
2018-05-02 14:18:58,391 [Thread-1:1700] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/login HTTP/1.1" 405 11703
2018-05-02 14:19:05,770 [Thread-3:9952] [django:166] [views:post] [INFO]- try to login
2018-05-02 14:19:05,884 [Thread-3:9952] [django:188] [views:post] [INFO]- login failed
2018-05-02 14:19:05,918 [Thread-3:9952] [django.server:124] [basehttp:log_message] [WARNING]- "POST /api/login HTTP/1.1" 401 11739
2018-05-02 14:26:06,349 [Thread-1:3584] [django:166] [views:post] [INFO]- try to login
2018-05-02 14:26:06,458 [Thread-1:3584] [django:189] [views:post] [INFO]- login failed
2018-05-02 14:26:06,524 [Thread-1:3584] [django.server:124] [basehttp:log_message] [WARNING]- "POST /api/login HTTP/1.1" 401 11739
2018-05-02 14:33:32,841 [Thread-1:524] [django:166] [views:post] [INFO]- try to login
2018-05-02 14:33:32,960 [Thread-1:524] [django:189] [views:post] [INFO]- login failed
2018-05-02 14:33:33,035 [Thread-1:524] [django.server:124] [basehttp:log_message] [WARNING]- "POST /api/login HTTP/1.1" 401 11739
2018-05-02 14:40:05,682 [Thread-1:3172] [django:166] [views:post] [INFO]- try to login
2018-05-02 14:40:05,686 [Thread-1:3172] [django:196] [views:post] [INFO]- login failed
2018-05-02 14:40:05,760 [Thread-1:3172] [django.server:124] [basehttp:log_message] [WARNING]- "POST /api/login HTTP/1.1" 400 11705
2018-05-02 14:40:14,716 [Thread-2:8676] [django:166] [views:post] [INFO]- try to login
2018-05-02 14:40:14,831 [Thread-2:8676] [django:190] [views:post] [INFO]- login failed
2018-05-02 14:40:14,861 [Thread-2:8676] [django.server:124] [basehttp:log_message] [WARNING]- "POST /api/login HTTP/1.1" 401 11739
2018-05-02 14:49:33,657 [Thread-1:11156] [django.request:93] [base:get_response] [WARNING]- Not Found: /
2018-05-02 14:49:33,659 [Thread-1:11156] [django.server:124] [basehttp:log_message] [WARNING]- "GET / HTTP/1.1" 404 2142
2018-05-02 14:49:37,904 [Thread-7:2376] [django.server:124] [basehttp:log_message] [INFO]- "GET /admin HTTP/1.1" 301 0
2018-05-02 14:49:37,938 [Thread-8:10492] [django.server:124] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 302 0
2018-05-02 14:49:37,989 [Thread-9:7232] [django.server:124] [basehttp:log_message] [INFO]- "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1856
2018-05-02 14:49:38,008 [Thread-11:4952] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/admin/css/login.css HTTP/1.1" 200 1203
2018-05-02 14:49:38,010 [Thread-10:10776] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/admin/css/base.css HTTP/1.1" 200 16106
2018-05-02 14:49:38,019 [Thread-12:5152] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/admin/css/responsive.css HTTP/1.1" 200 17894
2018-05-02 14:49:38,133 [Thread-13:1284] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
2018-05-02 14:49:38,155 [Thread-14:10580] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 80304
2018-05-02 14:49:38,181 [Thread-15:8712] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 81348
2018-05-02 14:49:45,307 [Thread-16:1436] [django.server:124] [basehttp:log_message] [INFO]- "POST /admin/login/?next=/admin/ HTTP/1.1" 200 2017
2018-05-02 14:49:45,405 [Thread-17:10432] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 82564
2018-05-02 14:51:18,122 [Thread-1:8704] [django.server:124] [basehttp:log_message] [INFO]- "POST /admin/login/?next=/admin/ HTTP/1.1" 200 2017
2018-05-02 14:53:59,970 [Thread-1:10696] [django.server:124] [basehttp:log_message] [INFO]- "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1856
2018-05-02 14:54:00,854 [Thread-2:10344] [django.server:124] [basehttp:log_message] [INFO]- "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1856
2018-05-02 14:54:06,138 [Thread-8:6796] [django.server:124] [basehttp:log_message] [INFO]- "POST /admin/login/?next=/admin/ HTTP/1.1" 200 2017
2018-05-02 14:57:24,494 [Thread-1:10076] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/question/ HTTP/1.1" 200 14347
2018-05-02 15:02:42,840 [MainThread:10328] [django.security.DisallowedHost:74] [exception:response_for_exception] [ERROR]- Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
2018-05-02 15:02:42,880 [MainThread:10328] [django.security.DisallowedHost:74] [exception:response_for_exception] [ERROR]- Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
2018-05-02 15:03:17,147 [Thread-7:7804] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/question/ HTTP/1.1" 200 15788
2018-05-02 15:10:58,356 [Thread-13:8728] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/paper/ HTTP/1.1" 200 14450
2018-05-02 15:12:27,273 [MainThread:6032] [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/online_testing/paper/
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tss\SE-TSS\backend\online_testing\views.py", line 55, in create
    num_choice = int(request.data.get('num_choice'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2018-05-02 15:12:52,448 [Thread-19:2344] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/paper/ HTTP/1.1" 200 14967
2018-05-02 15:13:40,881 [MainThread:2736] [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/online_testing/paper/
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tss\SE-TSS\backend\online_testing\views.py", line 55, in create
    num_choice = int(request.data.get('num_choice'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2018-05-02 15:13:55,430 [MainThread:7856] [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/online_testing/paper/
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tss\SE-TSS\backend\online_testing\views.py", line 55, in create
    num_choice = int(request.data.get('num_choice'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2018-05-02 15:15:32,690 [MainThread:8728] [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/online_testing/paper/
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tss\SE-TSS\backend\online_testing\views.py", line 79, in create
    question = Question().objects.filter(question_id=question_id)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\db\models\manager.py", line 178, in __get__
    raise AttributeError("Manager isn't accessible via %s instances" % cls.__name__)
AttributeError: Manager isn't accessible via Question instances
2018-05-02 15:15:51,811 [MainThread:9284] [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/online_testing/paper/
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tss\SE-TSS\backend\online_testing\views.py", line 80, in create
    score_list.append(question.level)
AttributeError: 'QuerySet' object has no attribute 'level'
2018-05-02 15:16:11,884 [Thread-25:11048] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/paper/ HTTP/1.1" 200 15478
2018-05-02 15:19:09,968 [Thread-31:11016] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/paper/ HTTP/1.1" 200 15478
2018-05-02 15:21:14,823 [Thread-37:10072] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/paper/ HTTP/1.1" 200 15478
2018-05-02 15:21:25,908 [Thread-1:10892] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/paper/ HTTP/1.1" 200 15478
2018-05-02 15:21:26,800 [Thread-2:8868] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/paper/ HTTP/1.1" 200 15478
2018-05-02 15:21:36,358 [Thread-9:8408] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/paper/1 HTTP/1.1" 301 0
2018-05-02 15:21:36,425 [Thread-8:9660] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/paper/1/ HTTP/1.1" 200 17566
2018-05-02 15:21:46,321 [Thread-14:10936] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/paper/2/ HTTP/1.1" 200 17564
2018-05-02 15:52:53,386 [Thread-1:8944] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/paper/2/ HTTP/1.1" 200 17564
2018-05-02 15:52:54,139 [Thread-2:8228] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/paper/2/ HTTP/1.1" 200 17564
2018-05-02 15:52:58,321 [Thread-7:4788] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/paper/ HTTP/1.1" 200 15478
2018-05-02 15:53:03,067 [Thread-8:6932] [django.request:93] [base:get_response] [WARNING]- Not Found: /api/online_testing/examination
2018-05-02 15:53:03,068 [Thread-8:6932] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/online_testing/examination HTTP/1.1" 404 13090
2018-05-02 15:53:56,603 [Thread-1:10792] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination HTTP/1.1" 301 0
2018-05-02 15:53:56,715 [Thread-2:10812] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/ HTTP/1.1" 200 14613
2018-05-02 15:53:56,739 [Thread-3:10156] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121200
2018-05-02 15:58:29,788 [Thread-7:10868] [django.server:124] [basehttp:log_message] [WARNING]- "POST /api/online_testing/examination/ HTTP/1.1" 400 14898
2018-05-02 15:59:22,368 [Thread-1:4516] [django.server:124] [basehttp:log_message] [INFO]- "POST /api/online_testing/examination/ HTTP/1.1" 201 14890
2018-05-02 15:59:33,136 [Thread-2:3024] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1 HTTP/1.1" 301 0
2018-05-02 15:59:33,164 [Thread-3:10476] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/ HTTP/1.1" 200 10237
2018-05-02 15:59:38,288 [Thread-4:8508] [django.request:93] [base:get_response] [WARNING]- Not Found: /api/online_testing/examination/1/start_time
2018-05-02 15:59:38,290 [Thread-4:8508] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/online_testing/examination/1/start_time HTTP/1.1" 404 16087
2018-05-02 15:59:51,106 [Thread-10:8096] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time HTTP/1.1" 301 0
2018-05-02 15:59:51,132 [Thread-11:10412] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 400 10226
2018-05-02 16:00:26,404 [Thread-14:4576] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/conservation HTTP/1.1" 301 0
2018-05-02 16:00:26,433 [Thread-15:9660] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/conservation/ HTTP/1.1" 200 10240
2018-05-02 16:00:31,038 [Thread-16:8680] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/conservation/ HTTP/1.1" 200 10240
2018-05-02 16:00:33,691 [Thread-17:9332] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/conservation/ HTTP/1.1" 200 10240
2018-05-02 16:00:41,156 [Thread-22:3012] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/ HTTP/1.1" 200 10237
2018-05-02 16:00:54,123 [Thread-1:2236] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/conservation/ HTTP/1.1" 200 10240
2018-05-02 16:00:57,205 [Thread-2:524] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/online_testing/examination/1/conservation/ HTTP/1.1" 400 10245
2018-05-02 16:00:59,682 [Thread-3:520] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/ HTTP/1.1" 200 10236
2018-05-02 16:01:04,839 [Thread-6:11156] [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/online_testing/examination/1/left_time/
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tss\SE-TSS\backend\online_testing\views.py", line 138, in left_time
    return Response({'left_time': (datetime.now() - exam.start_time).total_seconds()})
TypeError: can't subtract offset-naive and offset-aware datetimes
2018-05-02 16:01:04,899 [Thread-6:11156] [django.server:124] [basehttp:log_message] [ERROR]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 500 97560
2018-05-02 16:02:36,803 [Thread-1:10144] [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/online_testing/examination/1/left_time/
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tss\SE-TSS\backend\online_testing\views.py", line 139, in left_time
    return Response({'left_time': (datetime.now() - exam.start_time.replace(tzinfo=pytz.timezone('UTC'))  ).total_seconds()})
TypeError: can't subtract offset-naive and offset-aware datetimes
2018-05-02 16:02:36,870 [Thread-1:10144] [django.server:124] [basehttp:log_message] [ERROR]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 500 98078
2018-05-02 16:02:37,643 [Thread-2:11056] [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/online_testing/examination/1/left_time/
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tss\SE-TSS\backend\online_testing\views.py", line 139, in left_time
    return Response({'left_time': (datetime.now() - exam.start_time.replace(tzinfo=pytz.timezone('UTC'))  ).total_seconds()})
TypeError: can't subtract offset-naive and offset-aware datetimes
2018-05-02 16:02:37,710 [Thread-2:11056] [django.server:124] [basehttp:log_message] [ERROR]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 500 98078
2018-05-02 16:03:31,962 [Thread-1:9804] [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/online_testing/examination/1/left_time/
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tss\SE-TSS\backend\online_testing\views.py", line 140, in left_time
    return Response({'left_time': (datetime.now() - datetime(exam.start_time)).total_seconds()})
TypeError: an integer is required (got type datetime.datetime)
2018-05-02 16:03:32,026 [Thread-1:9804] [django.server:124] [basehttp:log_message] [ERROR]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 500 97959
2018-05-02 16:03:32,802 [Thread-2:10860] [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/online_testing/examination/1/left_time/
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tss\SE-TSS\backend\online_testing\views.py", line 140, in left_time
    return Response({'left_time': (datetime.now() - datetime(exam.start_time)).total_seconds()})
TypeError: an integer is required (got type datetime.datetime)
2018-05-02 16:03:32,881 [Thread-2:10860] [django.server:124] [basehttp:log_message] [ERROR]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 500 97959
2018-05-02 16:04:10,882 [Thread-1:1888] [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/online_testing/examination/1/left_time/
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tss\SE-TSS\backend\online_testing\views.py", line 141, in left_time
    return Response({'left_time': (datetime.now() - exam.start_time).total_seconds()})
TypeError: can't subtract offset-naive and offset-aware datetimes
2018-05-02 16:04:10,959 [Thread-1:1888] [django.server:124] [basehttp:log_message] [ERROR]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 500 97981
2018-05-02 16:04:11,614 [Thread-2:9504] [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/online_testing/examination/1/left_time/
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tss\SE-TSS\backend\online_testing\views.py", line 141, in left_time
    return Response({'left_time': (datetime.now() - exam.start_time).total_seconds()})
TypeError: can't subtract offset-naive and offset-aware datetimes
2018-05-02 16:04:11,708 [Thread-2:9504] [django.server:124] [basehttp:log_message] [ERROR]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 500 97981
2018-05-02 16:05:17,412 [Thread-1:9400] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10175
2018-05-02 16:05:19,453 [Thread-2:4936] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10175
2018-05-02 16:05:20,071 [Thread-3:9728] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10175
2018-05-02 16:05:20,790 [Thread-4:5956] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10175
2018-05-02 16:05:21,341 [Thread-5:2540] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10175
2018-05-02 16:05:21,842 [Thread-10:5888] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10175
2018-05-02 16:05:22,388 [Thread-11:10124] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10175
2018-05-02 16:05:22,919 [Thread-12:5800] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10175
2018-05-02 16:05:23,430 [Thread-13:7732] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10175
2018-05-02 16:05:23,949 [Thread-14:948] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10175
2018-05-02 16:05:24,547 [Thread-15:10628] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10175
2018-05-02 16:05:25,014 [Thread-16:9224] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10175
2018-05-02 16:05:25,478 [Thread-17:8680] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10175
2018-05-02 16:05:25,988 [Thread-18:9332] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10175
2018-05-02 16:06:56,135 [Thread-1:596] [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/online_testing/examination/1/left_time/
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tss\SE-TSS\backend\online_testing\views.py", line 141, in left_time
    return Response({'left_time': exam.duration * 60
AttributeError: 'Examination' object has no attribute 'duration'
2018-05-02 16:06:56,231 [Thread-1:596] [django.server:124] [basehttp:log_message] [ERROR]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 500 97158
2018-05-02 16:07:27,868 [Thread-1:8232] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10175
2018-05-02 16:07:29,684 [Thread-2:10336] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:07:30,244 [Thread-3:9036] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:07:31,115 [Thread-4:5784] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:07:31,369 [Thread-5:5924] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:07:31,581 [Thread-10:3604] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:07:31,812 [Thread-11:9840] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:07:31,967 [Thread-12:8384] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:07:32,172 [Thread-13:8832] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:07:32,363 [Thread-14:9564] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:07:32,495 [Thread-15:4796] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:07:32,636 [Thread-16:3928] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:07:32,795 [Thread-17:10692] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:07:32,964 [Thread-18:10084] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:07:33,099 [Thread-19:1684] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10183
2018-05-02 16:07:33,300 [Thread-20:11152] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10175
2018-05-02 16:07:33,490 [Thread-21:11260] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:07:33,632 [Thread-22:5256] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:07:33,791 [Thread-23:6488] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:07:33,988 [Thread-24:10824] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10175
2018-05-02 16:07:34,136 [Thread-25:10684] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:07:34,309 [Thread-26:8456] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:07:34,479 [Thread-27:10228] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:07:34,643 [Thread-28:5928] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:07:34,819 [Thread-29:760] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:07:35,007 [Thread-30:6120] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:07:36,122 [Thread-31:816] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:07:36,288 [Thread-32:6040] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:07:36,438 [Thread-33:600] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:11:58,473 [Thread-34:9252] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:11:59,058 [Thread-35:1280] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:11:59,738 [Thread-36:9120] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:11:59,883 [Thread-37:2380] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:00,186 [Thread-38:520] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:00,419 [Thread-39:11120] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:00,560 [Thread-40:11156] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10175
2018-05-02 16:12:00,872 [Thread-41:8988] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:01,017 [Thread-42:10756] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:01,180 [Thread-43:9148] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:01,317 [Thread-44:10184] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:01,475 [Thread-45:780] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10175
2018-05-02 16:12:01,816 [Thread-46:4424] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:01,943 [Thread-47:8940] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:02,281 [Thread-48:4392] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:02,411 [Thread-49:8032] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:02,561 [Thread-50:10048] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:02,720 [Thread-51:9232] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:02,866 [Thread-52:2324] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:03,026 [Thread-53:8916] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:03,219 [Thread-54:9512] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:03,549 [Thread-55:9368] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:03,665 [Thread-56:9700] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:03,833 [Thread-57:8692] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:04,025 [Thread-58:8828] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:04,166 [Thread-59:10720] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:04,338 [Thread-60:9860] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:04,540 [Thread-61:8488] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:04,726 [Thread-62:5156] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:04,859 [Thread-63:11208] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:05,041 [Thread-64:8924] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:05,178 [Thread-65:6088] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:05,310 [Thread-66:8248] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10183
2018-05-02 16:12:05,509 [Thread-67:6440] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:05,665 [Thread-68:11184] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:05,831 [Thread-69:10508] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:05,993 [Thread-70:9292] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:06,514 [Thread-71:9600] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:06,673 [Thread-72:9040] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:06,864 [Thread-73:5264] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:07,014 [Thread-74:9468] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:07,345 [Thread-75:10788] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:07,536 [Thread-76:6976] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:07,684 [Thread-77:3584] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:07,829 [Thread-78:7628] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:07,982 [Thread-79:8552] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:08,152 [Thread-80:9768] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:08,291 [Thread-81:10192] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:08,475 [Thread-82:4436] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:08,742 [Thread-83:196] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:10,850 [Thread-84:2428] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:10,993 [Thread-85:10996] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:11,168 [Thread-86:460] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 16:12:11,344 [Thread-87:9520] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1/left_time/ HTTP/1.1" 200 10176
2018-05-02 20:40:58,183 [Thread-1:9248] [django.request:93] [base:get_response] [WARNING]- Not Found: /
2018-05-02 20:40:58,204 [Thread-1:9248] [django.server:124] [basehttp:log_message] [WARNING]- "GET / HTTP/1.1" 404 2142
2018-05-02 20:40:58,667 [Thread-2:7532] [django.request:93] [base:get_response] [WARNING]- Not Found: /favicon.ico
2018-05-02 20:40:58,668 [Thread-2:7532] [django.server:124] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 2193
2018-05-02 20:41:04,150 [Thread-3:8504] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/question/ HTTP/1.1" 200 15788
2018-05-02 20:41:07,012 [Thread-4:2076] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/ HTTP/1.1" 200 10124
2018-05-02 20:41:10,818 [Thread-5:9164] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/admin/ HTTP/1.1" 403 9355
2018-05-02 20:41:45,711 [Thread-12:3080] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/student/ HTTP/1.1" 403 9377
2018-05-02 20:41:54,369 [Thread-13:7472] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/ HTTP/1.1" 200 10124
2018-05-02 20:41:59,586 [Thread-19:1404] [django.request:93] [base:get_response] [WARNING]- Not Found: /api/get
2018-05-02 20:41:59,588 [Thread-19:1404] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/get HTTP/1.1" 404 9323
2018-05-02 20:42:04,659 [Thread-20:8400] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/get_token HTTP/1.1" 405 12055
2018-05-02 20:42:17,057 [Thread-25:8468] [django.server:124] [basehttp:log_message] [WARNING]- "POST /api/get_token HTTP/1.1" 400 12095
2018-05-02 20:42:27,818 [Thread-26:9572] [django.server:124] [basehttp:log_message] [WARNING]- "POST /api/get_token HTTP/1.1" 400 12095
2018-05-02 20:46:45,663 [Thread-27:5736] [django.server:124] [basehttp:log_message] [WARNING]- "POST /api/get_token HTTP/1.1" 400 12095
2018-05-02 20:47:16,758 [Thread-28:7164] [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/bootstrap.min.css.map HTTP/1.1" 404 1744
2018-05-02 20:47:20,050 [Thread-29:9136] [django.server:124] [basehttp:log_message] [WARNING]- "POST /api/get_token HTTP/1.1" 400 12095
2018-05-02 20:47:20,318 [Thread-30:6640] [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/bootstrap.min.css.map HTTP/1.1" 404 1744
2018-05-02 20:51:39,255 [Thread-31:1812] [django.server:124] [basehttp:log_message] [INFO]- "POST /api/get_token HTTP/1.1" 200 12183
2018-05-02 20:52:06,621 [Thread-32:5448] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/login HTTP/1.1" 405 11703
2018-05-02 20:52:15,015 [Thread-33:7596] [django:166] [views:post] [INFO]- try to login
2018-05-02 20:52:15,528 [Thread-33:7596] [django:178] [views:post] [INFO]- login successfully
2018-05-02 20:52:15,663 [Thread-33:7596] [django.server:124] [basehttp:log_message] [INFO]- "POST /api/login HTTP/1.1" 200 11777
2018-05-02 21:02:18,030 [Thread-1:5592] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/ HTTP/1.1" 200 10157
2018-05-02 21:02:18,788 [Thread-2:9336] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/ HTTP/1.1" 200 10157
2018-05-02 21:02:20,876 [Thread-7:6300] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/admin/ HTTP/1.1" 200 14476
2018-05-02 21:02:32,397 [Thread-8:2616] [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/bootstrap.min.css.map HTTP/1.1" 404 1744
2018-05-02 21:02:38,778 [Thread-9:8640] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/admin/ HTTP/1.1" 200 14476
2018-05-02 21:02:39,026 [Thread-10:9944] [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/bootstrap.min.css.map HTTP/1.1" 404 1744
2018-05-02 21:04:42,320 [Thread-11:4444] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/admin/ HTTP/1.1" 200 14476
2018-05-02 21:04:43,208 [Thread-12:2180] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/admin/ HTTP/1.1" 200 14476
2018-05-02 21:04:43,820 [Thread-13:8896] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/admin/ HTTP/1.1" 200 14476
2018-05-02 21:04:44,475 [Thread-14:6616] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/admin/ HTTP/1.1" 200 14476
2018-05-02 21:07:15,277 [Thread-15:9828] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/admin/ HTTP/1.1" 200 14476
2018-05-02 21:07:16,046 [Thread-16:7888] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/admin/ HTTP/1.1" 200 14476
2018-05-02 21:07:16,571 [Thread-17:6520] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/admin/ HTTP/1.1" 200 14476
2018-05-02 21:07:22,537 [Thread-18:2028] [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/bootstrap.min.css.map HTTP/1.1" 404 1744
2018-05-02 21:07:25,849 [Thread-19:828] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/admin/ HTTP/1.1" 200 14476
2018-05-02 21:07:26,152 [Thread-20:3688] [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/bootstrap.min.css.map HTTP/1.1" 404 1744
2018-05-02 21:20:47,231 [Thread-1:7860] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/question/ HTTP/1.1" 200 15821
2018-05-02 21:20:47,569 [Thread-2:948] [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/bootstrap.min.css.map HTTP/1.1" 404 1744
2018-05-02 21:22:23,748 [Thread-1:7468] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/question/ HTTP/1.1" 200 15821
2018-05-02 21:22:30,061 [Thread-2:516] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/question/ HTTP/1.1" 200 15821
2018-05-02 21:23:02,220 [Thread-1:112] [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/online_testing/question/
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tss\SE-TSS\backend\online_testing\views.py", line 40, in list
    for i in request.session:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
KeyError: 0
2018-05-02 21:23:02,316 [Thread-1:112] [django.server:124] [basehttp:log_message] [ERROR]- "GET /api/online_testing/question/ HTTP/1.1" 500 100502
2018-05-02 22:00:00,783 [MainThread:3044] [django:166] [views:post] [INFO]- try to login
2018-05-02 22:00:01,183 [MainThread:3044] [django:178] [views:post] [INFO]- login successfully
2018-05-02 22:00:12,736 [MainThread:8792] [django:166] [views:post] [INFO]- try to login
2018-05-02 22:00:13,116 [MainThread:8792] [django:178] [views:post] [INFO]- login successfully
2018-05-02 22:12:26,278 [Thread-1:9984] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/question/ HTTP/1.1" 200 15821
2018-05-02 22:15:34,490 [Thread-5:8716] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/ HTTP/1.1" 200 10184
2018-05-02 22:15:35,192 [Thread-6:9828] [django.request:93] [base:get_response] [WARNING]- Not Found: /api/online_testin
2018-05-02 22:15:35,196 [Thread-6:9828] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/online_testin HTTP/1.1" 404 9353
2018-05-02 22:15:53,797 [Thread-12:9108] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/question/ HTTP/1.1" 200 15821
2018-05-02 22:20:16,760 [Thread-17:6496] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/question/1 HTTP/1.1" 301 0
2018-05-02 22:20:16,837 [Thread-18:1664] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/question/1/ HTTP/1.1" 200 16486
2018-05-02 22:20:37,728 [Thread-22:8456] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/ HTTP/1.1" 200 10184
2018-05-02 22:20:39,186 [Thread-23:9976] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/paper/ HTTP/1.1" 200 15511
2018-05-02 22:21:31,339 [Thread-29:5692] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/paper/1/ HTTP/1.1" 200 17599
2018-05-02 22:22:15,337 [Thread-41:9640] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/paper/2/ HTTP/1.1" 200 17597
2018-05-02 22:23:52,223 [Thread-47:4212] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/1 HTTP/1.1" 301 0
2018-05-02 22:23:52,267 [Thread-48:9360] [django.request:93] [base:get_response] [WARNING]- Not Found: /api/online_testing/examination/1/
2018-05-02 22:23:52,267 [Thread-48:9360] [django.server:124] [basehttp:log_message] [WARNING]- "GET /api/online_testing/examination/1/ HTTP/1.1" 404 10089
2018-05-02 22:23:57,888 [Thread-49:312] [django.server:124] [basehttp:log_message] [INFO]- "GET /api/online_testing/examination/ HTTP/1.1" 200 14373
